### ISSUE TITLE
Outside parameters for definition

### ISSUE THREAD

**Issue by vanhtuan0409** [sarulabs/di#1]
I hope this repo is still in maintenance.
My use case is, for every incoming request, I will generate a unique id for logging. There will be a Logging Definition with Request Scope that needs to be initialized a new instance for every request. This Logging Definition will use the generated unique id for logging.
How can I inject this unique id into Logging Definition or at least into Request Scope context 😄 
I hope to hear response from you

**Comment by sarulabs** [comment]
This repository is still under maintenance even though I don't have any plan to add new features.

You need to have a `Request` object in the request scope to store the id:

```go
type Request struct {
    ID string
}
```

The logger will use this object to retrieve the request id.

```go
di.Definition{
    Name: "request",
    Scope: di.Request,
    Build: func(ctx di.Context) (interface{}, error) {
        return NewRequest() // the Request constructor
    },
}

di.Definition{
    Name: "logger",
    Scope: di.Request,
    Build: func(ctx di.Context) (interface{}, error) {
        r := ctx.Get("request").(*Request)
        return NewLogger(r.ID)
    },
}
```

The `NewRequest` constructor may be in charge of generating the id.

If it is not an option, the id should be injected just after the creation of the request context:

```go
request, _ := app.SubContext()
defer request.Delete()

request.Get("request").(*Request).ID = GenerateID()
```
