### ISSUE TITLE
When using app.subcontainer is each one executed in it's own goroutine?

### ISSUE THREAD

**Issue by MostHated** [sarulabs/di#11]
Part of what I am using this for is for DB connections similar to what you have in the example, but I wanted to check if I needed to try and handle threading on my own or if this takes care of any threading already?

Here was how I was planning on doing it.

```Go
	{
		// --- Creates database connection object ----------------------------------------------------------------------
		Name:  "dbConn",
		Scope: di.App,
		Build: func(ctn di.Container) (interface{}, error) {
			var db appconfig.DbSettings
			var conn components.DbConfig
			dbconfig := db.GetDbConfig()
			dbConn := conn.ConnectDB(dbconfig)
			return dbConn, nil
		},
		Close: func(obj interface{}) error {
			return obj.(*components.DbConfig).Xorm.Close()
		},
	},
	{
		// --- Uses database connection object and returns a connection session ----------------------------------------
		Name:  "db",
		Scope: di.Request,
		Build: func(ctn di.Container) (interface{}, error) {
			conn := ctn.Get("dbConn").(*components.DbConfig).Xorm
			return conn, nil
		},
		Close: func(obj interface{}) error {
			return obj.(*components.DbConfig).Xorm.Close()
		},
	},
```

Thanks,
-MH

**Comment by sarulabs** [comment]
Hello,

this library does not create any goroutine. It is safe to use it in your own goroutines though.
That being said the code in the `Build` and `Close` functions (which is called when a container is created or deleted) can use objects that may be used in other goroutines. So depending on your application these objects may need to be thread-safe.

Concerning your example, I do not know the library you are using but it seems wrong. In the readme example (https://github.com/sarulabs/di/#examples), I have two services, a pool of connection and a connection. But you do not seem to create a new connection for each request. So you do not really need two services. The first one is enough. You can keep the second one if you want but it does not need to be in the request scope.

```go
{
    // --- Creates database connection object ----------------------------------------------------------------------
    Name:  "dbConn",
    Scope: di.App,
    Build: func(ctn di.Container) (interface{}, error) {
        var db appconfig.DbSettings
        var conn components.DbConfig
        dbconfig := db.GetDbConfig()
        dbConn := conn.ConnectDB(dbconfig)
        return dbConn, nil
    },
    Close: func(obj interface{}) error {
        return obj.(*components.DbConfig).Xorm.Close()
    },
},
{
    // --- Uses database connection object and returns a connection session ----------------------------------------
    Name:  "db",
    Scope: di.App,
    Build: func(ctn di.Container) (interface{}, error) {
        conn := ctn.Get("dbConn").(*components.DbConfig).Xorm
        return conn, nil
    },
},
```

The `Close` function in your second service closes the connection after each request. But as you do not create a new connection in the `Build` function, it is the app connection (the only one) that is closed. So I do not think your code should work for the second request. But maybe I missed something.

You do not need to add a mutex to this code if the `DbConfig.Xorm` attribute is not updated and is thread-safe. If you have a doubt, try to run your application with the `-race` option.

**Comment by MostHated** [comment]
Thanks for the reply. I suppose I was just a bit confused on the purpose of the send portions functionality. The way it looked, at least to me was, the first top portion was defining *how* to create a connection and then when you used the second portion in code it was using the defined connection above it to create a new connection session and use it, so I was under the impression that each time the second part was used it was a separate individual connection to the DB, which was why I asked if it happened to be in it's own goroutine. 

The code above works well, at least it seems like it's working well. I do know it works, I just might have to do some testing to see if it is working "well", as you mentioned perhaps do some -race testing. I suppose if I am not using it correctly, I might have to redo it and try and figure out the correct way to use it.

Thanks again for the reply, I do appreciate it.
-MH
