### ISSUE TITLE
is it possible to Remove checkname from Add method ?

### ISSUE THREAD

**Issue by henres** [sarulabs/di#15]
Hello here,

Like your di container, very easy to use and understand.

I came from symfony who use container and service definition.
And it's possible to overwrite every service: https://symfony.com/doc/current/service_container/service_decoration.html

For one of my project, it will be great to have this possibility.

Thanks for your awesome works !

**Comment by sarulabs** [comment]
Hello,

I'm glad you like the library.

I read the symfony documentation and that seems to be a good idea.

Not allowing to override a service provides little safety, but it limits a lot the possibilities of the library. I don't think that removing the `checkName` call can impact anyone. So I'll do it right away.

Regarding the decorator pattern, it can probably be included in the library too. Is this a feature you would like to use ?

**Comment by sarulabs** [comment]
`checkName` was removed in `v2.2.0`.

**Comment by henres** [comment]
Thanks ! I will try it !

**Comment by henres** [comment]
https://github.com/sarulabs/di/blob/0217505f010898b55e90f3c5336c5b8313a0d531/containerGetter.go#L40
```
	if ctn.builtList.Has(def.Name) {
		return nil, fmt.Errorf(
			"could not get `%s` because there is a cycle in the object definitions (%v)",
			def.Name, ctn.builtList.OrderedList(),
		)
	}
```
Still to be able to override a service in container build time.

**Comment by sarulabs** [comment]
Hello,

I do not really understand what you are trying to do.

The change I made impacted the `Builder.Add` method. When you override a definition, it works as if the first definition was never added to the `Builder`. Once the `Builder.Build` method is called, you get a `Container` and you can not change the definitions anymore.

If you have an error about a cycle in the object definitions, it is probably not related to this issue. Either you really have a cycle, or there is a bug in the cycle detection.


Could you provide me an example of code that does not work, so I can reproduce the problem ?

**Comment by henres** [comment]
I create a gin router with default groups in the main application:

```go

type GroupRouter struct {
	Path    string
	Actions []RouteAction
}

type RouteAction struct {
	Path   string
	Method string
	Action string
}

func NewRouter(builder *di.Builder) {
	builder.Add(
		di.Def{
			Name: "default.router",
			Build: func(container di.Container) (interface{}, error) {
				return Router{Router: gin.Default()}, nil
			},
		},
		di.Def{
			Name: "default.router.groups",
			Build: func(container di.Container) (interface{}, error) {
				return []GroupRouter{}, nil
			},
		},
	)
}

func (router *Router) AddPackagesRoute(container di.Container) {
	groupRouter := container.Get("default.router.groups").([]GroupRouter)
	for _, group := range groupRouter {
		router.addGroupToRouter(group, container)
	}
}

func (router *Router) addGroupToRouter(groupRouter GroupRouter, container di.Container) {

	group := router.Router.Group(groupRouter.Path)
	{
		for _, action := range groupRouter.Actions {

			reflect.ValueOf(group).MethodByName(action.Method).Call([]reflect.Value{
				reflect.ValueOf(action.Path),
				reflect.ValueOf(container.Get(action.Action)),
			})
		}
	}
}
```

In submodules,  I add to defaut.router.groups new route, like this:

```go

var ManagementApiRouter applicationRouter.GroupRouter = applicationRouter.GroupRouter{
	Path: "/api/management",
	Actions: []applicationRouter.RouteAction{
		{
			Path:   "/ping",
			Method: "GET",
			Action: "ping.controller.managament_api",
		},
		{
			Path:   "/forms",
			Method: "GET",
			Action: "get.forms.controller.managament_api",
		},
	},
}

func configureRouter(builder *di.Builder) {

	builder.Add(
		di.Def{
			Name: "default.router.groups",
			Build: func(container di.Container) (interface{}, error) {
				routerGroups := container.Get("default.router.groups").([]applicationRouter.GroupRouter)
				return append(routerGroups, router.ManagementApiRouter), nil
			},
		},
	)
}
```

When I do this, I have this errors :
```shell
panic: could not build `default.router.groups` because the build function panicked: could not get `default.router.groups` because there is a cycle in the object definitions ([default.router.groups])
```

**Comment by sarulabs** [comment]
So you have two definitions:

```go
di.Def{
    Name: "default.router.groups",
    Build: func(container di.Container) (interface{}, error) {
        return []GroupRouter{}, nil
    },
}

di.Def{
    Name: "default.router.groups",
    Build: func(container di.Container) (interface{}, error) {
        routerGroups := container.Get("default.router.groups").([]applicationRouter.GroupRouter)
        return append(routerGroups, router.ManagementApiRouter), nil
    },
}
```

The first one is replaced by the second one, and you have indeed a cycle (with only one element). You can not make a definition depend on itself.

To compare that to the symfony documentation, you used:

```yaml
# config/services.yaml
services:
    App\Mailer: ~

    # this replaces the old App\Mailer definition with the new one, the
    # old definition is lost
    App\Mailer:
        class: App\NewMailer
```

But I guess you wanted to do:

```yaml
# config/services.yaml
services:
    App\Mailer: ~

    App\DecoratingMailer:
        # overrides the App\Mailer service
        # but that service is still available as App\DecoratingMailer.inner
        decorates: App\Mailer
```

which is not currently possible. The definitions would have to be updated to something like this:

```go
di.Def{
    Name: "default.router.groups",
    Build: func(container di.Container) (interface{}, error) {
        return []GroupRouter{}, nil
    },
}

di.Def{
    Name: "default.router.groups.decorator",
    Decorator: di.DefDecorator{
        Name: "default.router.groups",
        Priority: 1,
    },
    Build: func(container di.Container) (interface{}, error) {
        routerGroups := container.Get("default.router.groups.decorator.inner").([]applicationRouter.GroupRouter)
        return append(routerGroups, router.ManagementApiRouter), nil
    },
}
```

It probably can be achieved by modifying only the `Builder`. I would need some time to specify this a little more.

Is it what you wanted to do ?

**Comment by henres** [comment]
Hum, finally, before service decoration, maybe something easier will be to make service tagging.
like: https://symfony.com/doc/current/service_container/tags.html
With service tagging, i don't need to create a service and override it. 
I just need to define some services tagged `routing` and in my router class I get all tagged services to define them in the router service.

What do you think ?

**Comment by sarulabs** [comment]
It is possible to add tags to a definition:
https://github.com/sarulabs/di/blob/bc5c1d2edc7b42440323a3f1c003f629ee589927/definition.go#L9

And you can get the definitions from the container:
https://github.com/sarulabs/di/blob/bc5c1d2edc7b42440323a3f1c003f629ee589927/containerInterface.go#L15 

It is not very practical but it should work.

**Comment by henres** [comment]
I see you are french, I am also, maybe there is a more simple way to discuss about this. Keybase maybe ?

**Comment by sarulabs** [comment]
I created a keybase account with the login `sarulabs` if it can help.

**Comment by henres** [comment]
I close the issue.
