### ISSUE TITLE
HTTPMiddleware returns http.HandlerFunc

### ISSUE THREAD

**Issue by inhobaek-wj** [sarulabs/di#24]
Hi,

I'm developing web application using echo web framework and your di framework.

To use both, I should wrap di as middleware of echo, and it is something like this.

```go
// DI.
multiWriter := io.MultiWriter(os.Stdout,logFile)

app := createApp(multiWriter)
defer app.Delete()

m := func(h http.Handler) http.Handler {
    return di.HTTPMiddleware(h, app, func(msg string){
        log.Println(msg)
    })
}

em := echo.WrapMiddleware(m)

e := echo.New()
e.Use(em)
```

The problme is `echo.WrapMiddleware` method takes `func(http.Handler) http.Handler` as parameter
and `di.HTTPMiddleware` returns `http.HandlerFunc`.

So  I had to modified `di.HTTPMiddleware` like this as a quick fix.

```go
func HTTPMiddleware(h http.Handler, app Container, logFunc func(msg string)) http.Handler {

    return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
        // create a request container from tha app container
        ctn, err := app.SubContainer()
        if err != nil {
            panic(err)
        }
        defer func() {
            if err := ctn.Delete(); err != nil && logFunc != nil {
                logFunc(err.Error())
            }
        }()
        // call the handler with a new request
        // containing the container in its context
        h.ServeHTTP(w, r.WithContext(
            context.WithValue(r.Context(), ContainerKey("di"), ctn),
        ))
    })
}
```

I'm not sure this is good idea.
So please suggest good solution for this.

Thank you for this awesome library, anyway.

**Comment by sarulabs** [comment]
Hi,

rewriting your own middleware is not a bad idea. It is even what I do in my applications. In you case you could write:

```go
m := func(h http.Handler) http.Handler {
    return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
        ctn, err := app.SubContainer()
        if err != nil {
            panic(err)
        }
        defer func() {
            if err := ctn.Delete(); err != nil {
                log.Println(err.Error())
            }
        }()
        h.ServeHTTP(w, r.WithContext(
            context.WithValue(r.Context(), di.ContainerKey("di"), ctn),
        ))
    })
}
```

Changing the signature of the `HTTPMiddleware` function is not something that I want to do, because it would be a breaking change.

That being said, I can add a new function if you want (`HTTPMiddlewareWithPureHandler` for example). But it will still have `app` and `logFunc` as parameters. So you will need to write the `func(h http.Handler) http.Handler` middleware yourself (without the logic part tough).

**Comment by inhobaek-wj** [comment]
I think your advice is best.

Thank you for reply.
